# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UseNode@1
  inputs:
    version: '12.x'
- task: Bash@3
  displayName: Updating GTAG and "updated" meta tag
  inputs:
    targetType: 'inline'
    script: |
      npm i replace-in-file
      cd $(build.sourcesDirectory)/html
      node $(build.sourcesDirectory)/pipeline/replace-gtag.js
      node $(build.sourcesDirectory)/pipeline/replace-updated.js
- task: Bash@3
  displayName: Minifying HTML and CSS
  inputs:
    targetType: 'inline'
    script: |
      cd $(build.sourcesDirectory)/pipeline/gulp
      npm i
      gulp
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)/pipeline/gulp/dist'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
