steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - infra-manager
      - deployments
      - apply
      - --deployment=ehint-static-deployment
      - --project=ehintstatic
      - --zone=southamerica-east1
      - --local-source=./deploy/production.yaml