steps:
  - name: "gcr.io/cloud-builders/terraform"
    args: ["init", "-backend-config=bucket=ehint-static-bucket", '-config-dir=terraform']
  - name: "gcr.io/cloud-builders/terraform"
    args: ["apply", "-auto-approve", '-config-dir=terraform']
